export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'

export const STORE_PROFILE_NAME = "STORE_PROFILE_NAME"